import express from "express";
const router = express.Router();
import { register, login, logout, isAuthenticated, sendOtp, verifyOtp, resetPassword} from "../controllers/authController.js";  
import userAuth from "../middleware/userAuth.js";
router.post("/register", register);
router.post("/login", login);
router.post("/logout", logout);
router.post("/send-otp", sendOtp);
router.post("/verify-otp", verifyOtp);
router.post("/is-auth", userAuth, isAuthenticated);
router.post("/reset-password",resetPassword);
export default router;
